import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'tertiary': 'rgb(var(--color-tertiary) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value>)',
        'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'error': 'rgb(var(--color-error) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
        'secondary': 'rgb(var(--color-secondary) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        'outline': 'rgb(var(--color-outline) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        'on-background': 'rgb(var(--color-on-background) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'background': 'rgb(var(--color-background) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        // Brand constants — static hex, do NOT flip with dark mode
        'slate-dark': '#21242E',
        'accent-orange': '#FA654D',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'masthead': ['Anton', 'Impact', 'sans-serif'],
        'display-hero': ['Newsreader', 'Georgia', 'serif'],
        'headline-lg': ['Newsreader', 'Georgia', 'serif'],
        'headline-md': ['Newsreader', 'Georgia', 'serif'],
        'headline-sm': ['Newsreader', 'Georgia', 'serif'],
        'body-lead': ['Newsreader', 'Georgia', 'serif'],
        'body-base': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'stat-lg': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: 'inherit',
            a: {
              color: '#FA654D',
              textDecoration: 'underline',
              fontWeight: '500',
              '&:hover': {
                opacity: '0.85',
              },
            },
            h1: {
              fontFamily: 'Newsreader, Georgia, serif',
              color: 'inherit',
            },
            h2: {
              fontFamily: 'Newsreader, Georgia, serif',
              fontWeight: '700',
              color: 'inherit',
              marginTop: '2.5rem',
              marginBottom: '1rem',
            },
            h3: {
              fontFamily: 'Newsreader, Georgia, serif',
              fontWeight: '600',
              color: 'inherit',
              marginTop: '2rem',
              marginBottom: '0.75rem',
            },
            h4: {
              fontFamily: 'Newsreader, Georgia, serif',
              fontWeight: '600',
              color: 'inherit',
              marginTop: '1.5rem',
              marginBottom: '0.5rem',
            },
            p: {
              marginTop: '0',
              marginBottom: '1.25rem',
              lineHeight: '1.75',
            },
            blockquote: {
              borderLeftColor: '#FA654D',
              borderLeftWidth: '4px',
              fontStyle: 'italic',
              color: 'inherit',
              paddingLeft: '1.25rem',
              paddingTop: '0.5rem',
              paddingBottom: '0.5rem',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
            },
            ul: {
              listStyleType: 'disc',
              paddingLeft: '1.5rem',
              marginTop: '1rem',
              marginBottom: '1.25rem',
            },
            ol: {
              listStyleType: 'decimal',
              paddingLeft: '1.5rem',
              marginTop: '1rem',
              marginBottom: '1.25rem',
            },
            li: {
              marginTop: '0.375rem',
              marginBottom: '0.375rem',
              lineHeight: '1.65',
            },
            strong: {
              fontWeight: '700',
              color: 'inherit',
            },
            figure: {
              marginTop: '2rem',
              marginBottom: '2rem',
            },
            img: {
              borderRadius: '0.75rem',
              marginLeft: 'auto',
              marginRight: 'auto',
            },
            figcaption: {
              textAlign: 'center',
              fontSize: '0.8125rem',
              color: 'rgb(var(--color-secondary))',
              marginTop: '0.5rem',
            },
            table: {
              width: '100%',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              borderCollapse: 'collapse',
            },
            th: {
              borderBottomWidth: '2px',
              borderBottomColor: 'rgb(var(--color-outline-variant) / 0.4)',
              padding: '0.75rem',
              fontWeight: '700',
              textAlign: 'left',
            },
            td: {
              borderBottomWidth: '1px',
              borderBottomColor: 'rgb(var(--color-outline-variant) / 0.2)',
              padding: '0.75rem',
            },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};

export default config;
