import { JSDOM } from 'jsdom';
const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
global.window = dom.window;
global.document = dom.window.document;
global.Node = dom.window.Node;

import { Editor } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import LinkExtension from '@tiptap/extension-link';
import { IconSpan, TableOfContentsBlock } from '../src/components/admin/TiptapEditor.tsx';
import { analyzeRankMathSEO } from '../src/lib/rankMathAnalysis.ts';

console.log('================================================================');
console.log('TESTING TABLE OF CONTENTS BLOCK & ICON GENERATION');
console.log('================================================================');

// 1. TEST CASE A: DOCUMENT WITH NO HEADINGS
console.log('\n--- 1. Testing Document with NO H2/H3 Headings ---');
const emptyEditor = new Editor({
  extensions: [StarterKit, LinkExtension, IconSpan, TableOfContentsBlock],
  content: '<p>This is a preliminary draft without any headings yet.</p>',
});

let emptyHeadingsCount = 0;
emptyEditor.state.doc.descendants((node) => {
  if (node.type.name === 'heading') {
    const level = node.attrs.level;
    if (level === 2 || level === 3) emptyHeadingsCount++;
  }
});

console.log(`Headings Detected: ${emptyHeadingsCount}`);
console.log('Insert TOC Button State:', emptyHeadingsCount === 0 ? 'DISABLED (Correct: greyed out with warning)' : 'ENABLED');

// 2. TEST CASE B: DOCUMENT WITH REAL H2 & H3 HEADINGS
console.log('\n--- 2. Testing Document with 2 Real H2 Headings and 1 H3 Heading ---');
const populatedEditor = new Editor({
  extensions: [StarterKit, LinkExtension, IconSpan, TableOfContentsBlock],
  content: `
    <h2>The Anatomy of Fast Checkout Failure</h2>
    <p>Fast burst onto the Silicon Valley scene promising one-click payments.</p>
    <h3>Structural Burn Rate Acceleration</h3>
    <p>Internal metrics revealed unsustainable cash depletion exceeding $10M monthly.</p>
    <h2>Forensic Evidence from SEC and Court Filings</h2>
    <p>Bankruptcy court records confirm gross payments volume fell 95% below projections.</p>
  `,
});

// Scan headings
const headings = [];
populatedEditor.state.doc.descendants((node) => {
  if (node.type.name === 'heading') {
    const level = node.attrs.level;
    if (level === 2 || level === 3) {
      const text = node.textContent.trim();
      const id = text.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-');
      headings.push({ level, text, id });
    }
  }
});

console.log(`Headings Detected: ${headings.length}`);
headings.forEach((h, i) => console.log(`  ${i + 1}. [H${h.level}] "${h.text}" -> Anchor ID: #${h.id}`));

// Generate and insert TOC block
const itemsHtml = headings
  .map(
    (h) =>
      `<li class="${h.level === 3 ? 'ml-5 list-circle text-on-surface-variant' : 'list-disc font-medium'} my-1.5"><a href="#${h.id}" class="text-primary hover:underline">${h.text}</a></li>`
  )
  .join('');

const tocHtml = `<div data-type="table-of-contents" class="toc-container my-6 p-5 rounded-2xl bg-surface-container-low/80 border border-outline-variant/40 not-prose"><p class="text-xs font-bold uppercase tracking-wider text-secondary mb-3 flex items-center gap-1.5"><span class="material-symbols-outlined text-[18px] text-primary">format_list_bulleted</span> Table of Contents (${headings.length} Sections)</p><ul class="space-y-1 text-sm pl-4">${itemsHtml}</ul></div><p></p>`;

populatedEditor.commands.insertContent(tocHtml);

const outputHtml = populatedEditor.getHTML();
const outputJson = populatedEditor.getJSON();

console.log('\n--- 3. Verifying Generated TOC Block HTML & Structure ---');
console.log('Output HTML generated by Tiptap:');
console.log(outputHtml);

// Verification checks
const hasMaterialSymbolSpan = outputHtml.includes('<span class="material-symbols-outlined');
const hasTocDataType = outputHtml.includes('data-type="table-of-contents"');
const hasClickableH2Link1 = outputHtml.includes('href="#the-anatomy-of-fast-checkout-failure"');
const hasClickableH3Link = outputHtml.includes('href="#structural-burn-rate-acceleration"');
const hasClickableH2Link2 = outputHtml.includes('href="#forensic-evidence-from-sec-and-court-filings"');
const hasNoRawTextIcon = !outputHtml.includes('<p>format_list_bulleted') && hasMaterialSymbolSpan;

console.log('\nVerification Checklist:');
console.log(`- Material icon wrapped in proper <span class="material-symbols-outlined">: ${hasMaterialSymbolSpan ? 'PASS' : 'FAIL'}`);
console.log(`- Not dropped as raw unclassed text: ${hasNoRawTextIcon ? 'PASS' : 'FAIL'}`);
console.log(`- Has data-type="table-of-contents" container: ${hasTocDataType ? 'PASS' : 'FAIL'}`);
console.log(`- Clickable link to H2 #1 (The Anatomy of Fast Checkout Failure): ${hasClickableH2Link1 ? 'PASS' : 'FAIL'}`);
console.log(`- Clickable link to H3 (Structural Burn Rate Acceleration): ${hasClickableH3Link ? 'PASS' : 'FAIL'}`);
console.log(`- Clickable link to H2 #2 (Forensic Evidence from SEC and Court Filings): ${hasClickableH2Link2 ? 'PASS' : 'FAIL'}`);

// Rank Math analysis verification
const analysis = analyzeRankMathSEO({
  title: 'Fast Checkout Failure Case Study',
  slug: 'fast-checkout-failure',
  metaDescription: 'Autopsy of Fast checkout failure',
  focusKeyword: 'Fast checkout failure',
  doc: outputJson,
});

const tocCheck = analysis.groups.contentReadability.checks.find(c => c.id === 'content-toc-present');
console.log(`- Rank Math TOC Check: ${tocCheck?.status.toUpperCase()} ("${tocCheck?.message}")`);

const allPass =
  emptyHeadingsCount === 0 &&
  headings.length === 3 &&
  hasMaterialSymbolSpan &&
  hasNoRawTextIcon &&
  hasTocDataType &&
  hasClickableH2Link1 &&
  hasClickableH3Link &&
  hasClickableH2Link2 &&
  tocCheck?.status === 'pass';

if (allPass) {
  console.log('\n================================================================');
  console.log('ALL TOC BLOCK & ICON VERIFICATION CHECKS PASSED');
  console.log('================================================================');
  process.exit(0);
} else {
  console.error('\nFAILED: One or more checks did not pass.');
  process.exit(1);
}
